### ISSUE TITLE
Undocumented dependency on ember-truth-helpers

### ISSUE THREAD

**Issue by dfreeman** [salsify/ember-exclaim#9]
We're using the `{{or` helper [here](https://github.com/salsify/ember-exclaim/blob/master/addon/components/exclaim-ui/template.hbs#L2). We should either add `ember-truth-helpers` to `dependencies` or (probably better) make that value a computed property.

📎 @deverstalmage

**Comment by deverstalmage** [comment]
Fixed in https://github.com/salsify/ember-exclaim/pull/19
